/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2025-02-28 06:03:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.gem.generic.editor.binary;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.iplass.mtp.auth.AuthContext;
import org.iplass.mtp.entity.permission.EntityPropertyPermission;
import org.iplass.mtp.entity.BinaryReference;
import org.iplass.mtp.entity.definition.EntityDefinition;
import org.iplass.mtp.entity.definition.PropertyDefinition;
import org.iplass.mtp.util.StringUtil;
import org.iplass.mtp.view.generic.editor.BinaryPropertyEditor;
import org.iplass.mtp.view.generic.editor.BinaryPropertyEditor.BinaryDisplayType;
import org.iplass.mtp.web.template.TemplateUtil;
import org.iplass.mtp.web.template.TemplateUtil.TokenOutputType;
import org.iplass.gem.command.binary.DownloadCommand;
import org.iplass.gem.command.binary.UploadCommand;
import org.iplass.gem.command.Constants;

public final class BinaryPropertyEditor_005fEdit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


	String url(BinaryReference br, String action) {
		String url = action + "?" + Constants.ID + "=" + br.getLobId();
		if (br.getDefinitionName() != null) {
			url = url + "&" + Constants.DEF_NAME + "=" + br.getDefinitionName()
				+ "&" + Constants.PROP_NAME + "=" + br.getPropertyName();
		}
		return url;
	}

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_1;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_2;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("m:esc", org.iplass.mtp.web.template.ELFunctions.class, "esc", new Class[] {java.lang.String.class});
  _jspx_fnmap_1= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("m:rs", org.iplass.mtp.web.template.ELFunctions.class, "rs", new Class[] {java.lang.String.class, java.lang.String.class});
  _jspx_fnmap_2= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("m:fixToken", org.iplass.mtp.web.template.ELFunctions.class, "fixToken", new Class[] {});
}

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/mtp.tld", Long.valueOf(1738207446000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1737625086258L));
    _jspx_dependants.put("jar:file:/C:/pleiades/2024-12/workspace/Portal_Mock/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Portal_Mock/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664421078000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(23);
    _jspx_imports_classes.add("java.util.Arrays");
    _jspx_imports_classes.add("org.iplass.mtp.entity.definition.PropertyDefinition");
    _jspx_imports_classes.add("org.iplass.gem.command.binary.UploadCommand");
    _jspx_imports_classes.add("org.iplass.mtp.view.generic.editor.BinaryPropertyEditor");
    _jspx_imports_classes.add("org.iplass.mtp.auth.AuthContext");
    _jspx_imports_classes.add("org.iplass.mtp.entity.permission.EntityPropertyPermission");
    _jspx_imports_classes.add("org.iplass.mtp.web.template.TemplateUtil.TokenOutputType");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("org.iplass.mtp.util.StringUtil");
    _jspx_imports_classes.add("org.iplass.mtp.entity.BinaryReference");
    _jspx_imports_classes.add("org.iplass.gem.command.binary.DownloadCommand");
    _jspx_imports_classes.add("org.iplass.mtp.entity.definition.EntityDefinition");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.iplass.mtp.view.generic.editor.BinaryPropertyEditor.BinaryDisplayType");
    _jspx_imports_classes.add("org.iplass.gem.command.Constants");
    _jspx_imports_classes.add("org.iplass.mtp.web.template.TemplateUtil");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	BinaryPropertyEditor editor = (BinaryPropertyEditor) request.getAttribute(Constants.EDITOR_EDITOR);
	Object value = request.getAttribute(Constants.EDITOR_PROP_VALUE);
	PropertyDefinition pd = (PropertyDefinition) request.getAttribute(Constants.EDITOR_PROPERTY_DEFINITION);
	String execType = (String) request.getAttribute(Constants.EXEC_TYPE);
	Boolean nestDummyRow = (Boolean) request.getAttribute(Constants.EDITOR_REF_NEST_DUMMY_ROW);

	Boolean isVirtual = (Boolean) request.getAttribute(Constants.IS_VIRTUAL);
	if (isVirtual == null) isVirtual = false;

	boolean isInsert = Constants.EXEC_TYPE_INSERT.equals(execType);
	String defName = (String)request.getAttribute(Constants.DEF_NAME);
	String propName = editor.getPropertyName();
	AuthContext auth = AuthContext.getCurrentContext();
	boolean isEditable = true;
	if (isVirtual) {
		isEditable = true;//仮想プロパティは権限チェック要らない
	} else {
		if(isInsert) {
			isEditable = auth.checkPermission(new EntityPropertyPermission(defName, pd.getName(), EntityPropertyPermission.Action.CREATE));
		} else {
			isEditable = auth.checkPermission(new EntityPropertyPermission(defName, pd.getName(), EntityPropertyPermission.Action.UPDATE));
		}
	}
	boolean updatable = ((pd == null || pd.isUpdatable()) || isInsert) && isEditable;

	//詳細編集
	if (editor.getDisplayType() != BinaryDisplayType.HIDDEN && editor.getDisplayType() != BinaryDisplayType.LABEL && updatable) {

		boolean hideDeleteButton = editor.isHideDeleteButton();
		boolean hideSelectButton = editor.isHideSelectButton();

		String contextPath = TemplateUtil.getTenantContextPath();
		String upload = "";
		if (StringUtil.isNotBlank(editor.getUploadActionName())) {
			upload = contextPath + "/" + editor.getUploadActionName();
		} else {
			upload = contextPath + "/" + UploadCommand.ACTION_NAME;
		}

		String download = "";
		String ref = contextPath + "/" + DownloadCommand.REFERENCE_ACTION_NAME;
		if (StringUtil.isNotBlank(editor.getDownloadActionName())) {
			download = contextPath + "/" + editor.getDownloadActionName();
		} else {
			download = contextPath + "/" + DownloadCommand.DOWNLOAD_ACTION_NAME;
		}
		String pdfviewer = contextPath + "/" + DownloadCommand.PDFVIEWER_ACTION_NAME;
		String imgviewer = contextPath + "/" + DownloadCommand.IMGVIEWER_ACTION_NAME;

		String width = "";
		if (editor.getWidth() > 0) {
			width = " width=\"" + editor.getWidth() + "\"";
		}
		String height = "";
		if (editor.getHeight() > 0) {
			height = " height=\"" + editor.getHeight() + "\"";
		}

		String target = "";
		if (editor.isOpenNewTab()) {
			target = " target=\"_blank\"";
		}

		String displayType = editor.getDisplayType().name();

		String ulId = "ul_" + propName;
		String fileId = "file_" + propName;

		List<BinaryReference> brList = new ArrayList<BinaryReference>();
		if (value instanceof BinaryReference[]) {
			brList.addAll(Arrays.asList((BinaryReference[]) value));
		} else if (value instanceof BinaryReference) {
			brList.add((BinaryReference)value);
		}
		int length = brList.size();

		String style = length >= pd.getMultiplicity() ? "display : none;" : "";
		String cls = "";
		if (nestDummyRow != null && nestDummyRow) {
			cls = "";
		} else {
			cls = "upload-button";
		}
		String multiple = "";
		if (pd.getMultiplicity() > 1) multiple = "multiple";

		String viewName = (String)request.getAttribute(Constants.VIEW_NAME);
		if (viewName == null) {
			viewName = "";
		}
		// NOTE ネストプロパティの場合、defName ではネスト先のエンティティ名が取得できてしまう。
		//      entityDefinition キーで取得する値は表示しているビューのエンティティ定義なので、そこからエンティティ名を取得する
		EntityDefinition entityDefinition = (EntityDefinition)request.getAttribute(Constants.ENTITY_DEFINITION);
		String rootDefName = defName;
		if (entityDefinition != null) {
			rootDefName = entityDefinition.getName();
		}

		if (request.getAttribute(Constants.UPLOAD_LIB_LOADED) == null) {
			request.setAttribute(Constants.UPLOAD_LIB_LOADED, true);

      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m:esc(staticContentPath)}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("/webjars/blueimp-file-upload/10.32.0/js/jquery.fileupload.js?cv=");
      out.print(TemplateUtil.getAPIVersion());
      out.write("\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m:esc(staticContentPath)}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("/webjars/blueimp-file-upload/10.32.0/js/jquery.iframe-transport.js?cv=");
      out.print(TemplateUtil.getAPIVersion());
      out.write("\"></script>\n");

		}
		if (!hideSelectButton){

      out.write("<input type=\"file\" id=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(161,23) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue(fileId );
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      out.write("\" name=\"filePath\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m:rs('mtp-gem-messages', 'generic.editor.binary.BinaryPropertyEditor_Edit.upload')}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1));
      out.write("\"\n");
      out.write(" style=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(162,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue(style );
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      out.write("\" class=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(162,45) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue(cls );
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      out.write("\" data-pname=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(162,85) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue(propName );
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      out.write("\" data-displayType=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(162,136) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue(displayType);
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      out.write("\"\n");
      out.write(" data-binCount=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f5.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(163,16) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f5.setValue(length );
      int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
      if (_jspx_th_c_005fout_005f5.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
      out.write("\" data-uploadUrl=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f6 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f6.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(163,64) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f6.setValue(upload );
      int _jspx_eval_c_005fout_005f6 = _jspx_th_c_005fout_005f6.doStartTag();
      if (_jspx_th_c_005fout_005f6.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f6);
      out.write("\" data-downloadUrl=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f7 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f7.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(163,114) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f7.setValue(download );
      int _jspx_eval_c_005fout_005f7 = _jspx_th_c_005fout_005f7.doStartTag();
      if (_jspx_th_c_005fout_005f7.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f7);
      out.write("\" data-refUrl=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f8 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f8.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(163,161) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f8.setValue(ref );
      int _jspx_eval_c_005fout_005f8 = _jspx_th_c_005fout_005f8.doStartTag();
      if (_jspx_th_c_005fout_005f8.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f8);
      out.write("\"\n");
      out.write(" data-pdfviewerUrl=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f9 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f9.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(164,20) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f9.setValue(pdfviewer );
      int _jspx_eval_c_005fout_005f9 = _jspx_th_c_005fout_005f9.doStartTag();
      if (_jspx_th_c_005fout_005f9.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f9);
      out.write("\" data-usePdfjs=\"");
      out.print(editor.isUsePdfjs());
      out.write("\"\n");
      out.write(" data-imgviewerUrl=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f10 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f10.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(165,20) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f10.setValue(imgviewer );
      int _jspx_eval_c_005fout_005f10 = _jspx_th_c_005fout_005f10.doStartTag();
      if (_jspx_th_c_005fout_005f10.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f10);
      out.write("\" data-useImageViewer=\"");
      out.print(editor.isUseImageViewer());
      out.write("\"\n");
      out.write(" data-showImageRotateButton=\"");
      out.print(editor.isShowImageRotateButton() );
      out.write("\"  data-openNewTab=\"");
      out.print(editor.isOpenNewTab() );
      out.write("\"\n");
      out.write(" data-multiplicity=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f11 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f11.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f11.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(167,20) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f11.setValue(pd.getMultiplicity() );
      int _jspx_eval_c_005fout_005f11 = _jspx_th_c_005fout_005f11.doStartTag();
      if (_jspx_th_c_005fout_005f11.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f11);
      out.write("\" data-binWidth=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f12 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f12.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f12.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(167,81) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f12.setValue(editor.getWidth() );
      int _jspx_eval_c_005fout_005f12 = _jspx_th_c_005fout_005f12.doStartTag();
      if (_jspx_th_c_005fout_005f12.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f12);
      out.write("\"\n");
      out.write(" data-binHeight=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f13 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f13.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f13.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(168,17) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f13.setValue(editor.getHeight() );
      int _jspx_eval_c_005fout_005f13 = _jspx_th_c_005fout_005f13.doStartTag();
      if (_jspx_th_c_005fout_005f13.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f13);
      out.write("\" data-token=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m:fixToken()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_2));
      out.write('"');
      out.write(' ');
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f14 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f14.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f14.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(168,90) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f14.setValue(multiple);
      int _jspx_eval_c_005fout_005f14 = _jspx_th_c_005fout_005f14.doStartTag();
      if (_jspx_th_c_005fout_005f14.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f14);
      out.write(" \n");
      out.write(" data-vname=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f15 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f15.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f15.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(169,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f15.setValue(viewName );
      int _jspx_eval_c_005fout_005f15 = _jspx_th_c_005fout_005f15.doStartTag();
      if (_jspx_th_c_005fout_005f15.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f15);
      out.write("\" data-dname=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f16 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f16.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f16.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(169,58) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f16.setValue(rootDefName );
      int _jspx_eval_c_005fout_005f16 = _jspx_th_c_005fout_005f16.doStartTag();
      if (_jspx_th_c_005fout_005f16.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f16);
      out.write("\"\n");
      out.write(" />\n");
      out.write(" ");

		}
 
      out.write("<div>\n");
      out.write("<span id=\"em_");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f17 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f17.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f17.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(176,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f17.setValue(propName );
      int _jspx_eval_c_005fout_005f17 = _jspx_th_c_005fout_005f17.doStartTag();
      if (_jspx_th_c_005fout_005f17.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f17);
      out.write("\" class=\"ul_error error\" style=\"display:none;\" ></span>\n");
      out.write("<p id=\"img_");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f18 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f18.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f18.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(177,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f18.setValue(propName );
      int _jspx_eval_c_005fout_005f18 = _jspx_th_c_005fout_005f18.doStartTag();
      if (_jspx_th_c_005fout_005f18.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f18);
      out.write("\" class=\"loading\" style=\"display:none;\" />\n");
      out.write("</div>\n");
      out.write("<ul id=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f19 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f19.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f19.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(179,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f19.setValue(ulId );
      int _jspx_eval_c_005fout_005f19 = _jspx_th_c_005fout_005f19.doStartTag();
      if (_jspx_th_c_005fout_005f19.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f19);
      out.write('"');
      out.write('>');
      out.write('\n');

		String listStyle = "";
		if (editor.getDisplayType() == BinaryDisplayType.PREVIEW) {
			listStyle = "noimage";
		}
		for (int i = 0; i < brList.size(); i++) {
			BinaryReference br = brList.get(i);
			String liId = "li_" + propName + i;

      out.write("<li id=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f20 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f20.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f20.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(189,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f20.setValue(liId );
      int _jspx_eval_c_005fout_005f20 = _jspx_th_c_005fout_005f20.doStartTag();
      if (_jspx_th_c_005fout_005f20.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f20);
      out.write("\" class=\"list-bin ");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f21 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f21.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f21.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(189,53) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f21.setValue(listStyle );
      int _jspx_eval_c_005fout_005f21 = _jspx_th_c_005fout_005f21.doStartTag();
      if (_jspx_th_c_005fout_005f21.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f21);
      out.write('"');
      out.write('>');
      out.write('\n');

			//ファイルリンク
			if (editor.getDisplayType() == BinaryDisplayType.BINARY || editor.getDisplayType() == BinaryDisplayType.LINK) {
				if (br.getType().indexOf("application/pdf") != -1 && editor.isUsePdfjs()) {
					//PDFViewer
					String pdfPath = pdfviewer+ "?file=" + URLEncoder.encode(url(br, download), "utf-8");

      out.write("<a href=\"");
      out.print(pdfPath);
      out.write('"');
      out.write(' ');
      out.print(target );
      out.write(" class=\"link-bin\">");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f22 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f22.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f22.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(197,53) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f22.setValue(br.getName() );
      int _jspx_eval_c_005fout_005f22 = _jspx_th_c_005fout_005f22.doStartTag();
      if (_jspx_th_c_005fout_005f22.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f22);
      out.write("</a>\n");

				} else if (br.getType().indexOf("image") != -1 && editor.isUseImageViewer() && editor.isOpenNewTab()) {
					//ImageViewer＋別タブ

      out.write("<a href=\"javascript:void(0)\" data-viewerUrl=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f23 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f23.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f23.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(202,45) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f23.setValue(url(br, imgviewer) );
      int _jspx_eval_c_005fout_005f23 = _jspx_th_c_005fout_005f23.doStartTag();
      if (_jspx_th_c_005fout_005f23.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f23);
      out.write("\" data-lobid=\"");
      out.print(br.getLobId() );
      out.write("\" class=\"link-bin img-viewer\" onclick=\"showImageViewer(this);\">");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f24 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f24.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f24.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(202,183) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f24.setValue(br.getName() );
      int _jspx_eval_c_005fout_005f24 = _jspx_th_c_005fout_005f24.doStartTag();
      if (_jspx_th_c_005fout_005f24.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f24);
      out.write("</a>\n");

				} else {
					//Download

      out.write("<a href=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f25 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f25.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f25.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(207,9) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f25.setValue(url(br, download) );
      int _jspx_eval_c_005fout_005f25 = _jspx_th_c_005fout_005f25.doStartTag();
      if (_jspx_th_c_005fout_005f25.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f25);
      out.write('"');
      out.write(' ');
      out.print(target );
      out.write(" class=\"link-bin\">");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f26 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f26.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f26.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(207,82) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f26.setValue(br.getName() );
      int _jspx_eval_c_005fout_005f26 = _jspx_th_c_005fout_005f26.doStartTag();
      if (_jspx_th_c_005fout_005f26.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f26);
      out.write("</a>\n");

				}
			}

			//画像ローテ―トボタン
			if (editor.isShowImageRotateButton() && br.getType().indexOf("image") != -1) {
				if (editor.getDisplayType() == BinaryDisplayType.BINARY || editor.getDisplayType() == BinaryDisplayType.PREVIEW) {

      out.write("<span class=\"viewer-toolbar\" style=\"display:inline-block\">\n");
      out.write("<ul>\n");
      out.write("<li class=\"viewer-rotate-left\" onclick=\"rotateImage('");
      out.print(br.getLobId() );
      out.write("', -90)\"></li>\n");
      out.write("<li class=\"viewer-rotate-right\" onclick=\"rotateImage('");
      out.print(br.getLobId() );
      out.write("', 90)\"></li>\n");
      out.write("</ul>\n");
      out.write("</span>\n");

				}
			}

			//削除ボタン
			if (!hideDeleteButton){

      out.write("<a href=\"javascript:void(0)\" class=\"binaryDelete del-btn link-bin\" data-fileId=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f27 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f27.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f27.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(229,81) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f27.setValue(fileId );
      int _jspx_eval_c_005fout_005f27 = _jspx_th_c_005fout_005f27.doStartTag();
      if (_jspx_th_c_005fout_005f27.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f27);
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m:rs(\"mtp-gem-messages\", \"generic.editor.binary.BinaryPropertyEditor_Edit.delete\")}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1));
      out.write("</a>\n");

			}

			if (editor.getDisplayType() == BinaryDisplayType.BINARY || editor.getDisplayType() == BinaryDisplayType.PREVIEW) {
				if (br.getType().indexOf("image") != -1) {

      out.write("<p>\n");

					if (editor.isUseImageViewer() && editor.isOpenNewTab()) {
						//別タブ

      out.write("<img src=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f28 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f28.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f28.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(241,10) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f28.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f28 = _jspx_th_c_005fout_005f28.doStartTag();
      if (_jspx_th_c_005fout_005f28.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f28);
      out.write("\" alt=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f29 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f29.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f29.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(241,53) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f29.setValue(br.getName() );
      int _jspx_eval_c_005fout_005f29 = _jspx_th_c_005fout_005f29.doStartTag();
      if (_jspx_th_c_005fout_005f29.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f29);
      out.write("\" onload=\"imageLoad()\" ");
      out.print(width + height );
      out.write(" data-lobid=\"");
      out.print(br.getLobId() );
      out.write("\" class=\"img-viewer\" onclick=\"showImageViewer(this);\" data-viewerUrl=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f30 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f30.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f30.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(241,234) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f30.setValue(url(br, imgviewer) );
      int _jspx_eval_c_005fout_005f30 = _jspx_th_c_005fout_005f30.doStartTag();
      if (_jspx_th_c_005fout_005f30.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f30);
      out.write("\" />\n");

					} else {
						if (editor.isUseImageViewer()) {
							//Inline

      out.write("<img src=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f31 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f31.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f31.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(247,10) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f31.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f31 = _jspx_th_c_005fout_005f31.doStartTag();
      if (_jspx_th_c_005fout_005f31.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f31);
      out.write("\" alt=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f32 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f32.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f32.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(247,53) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f32.setValue(br.getName() );
      int _jspx_eval_c_005fout_005f32 = _jspx_th_c_005fout_005f32.doStartTag();
      if (_jspx_th_c_005fout_005f32.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f32);
      out.write("\" onload=\"imageLoad()\" ");
      out.print(width + height );
      out.write(" data-lobid=\"");
      out.print(br.getLobId() );
      out.write("\" class=\"img-viewer\" onclick=\"inlineImageViewer(this);\" />\n");

						} else {

      out.write("<img src=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f33 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f33.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f33.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(251,10) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f33.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f33 = _jspx_th_c_005fout_005f33.doStartTag();
      if (_jspx_th_c_005fout_005f33.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f33);
      out.write("\" alt=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f34 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f34.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f34.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(251,53) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f34.setValue(br.getName() );
      int _jspx_eval_c_005fout_005f34 = _jspx_th_c_005fout_005f34.doStartTag();
      if (_jspx_th_c_005fout_005f34.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f34);
      out.write("\" onload=\"imageLoad()\" ");
      out.print(width + height );
      out.write(" data-lobid=\"");
      out.print(br.getLobId() );
      out.write("\" />\n");

						}
					}

      out.write("<span class=\"dummy\"></span>\n");
      out.write("</p>\n");

				} else if (br.getType().indexOf("application/x-shockwave-flash") != -1) {

      out.write("<p>\n");
      out.write("<object data=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f35 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f35.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f35.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(262,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f35.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f35 = _jspx_th_c_005fout_005f35.doStartTag();
      if (_jspx_th_c_005fout_005f35.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f35);
      out.write("\" type=\"application/x-shockwave-flash\" ");
      out.print(width + height );
      out.write(" >\n");
      out.write("<param name=\"movie\" value=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f36 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f36.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f36.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(263,27) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f36.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f36 = _jspx_th_c_005fout_005f36.doStartTag();
      if (_jspx_th_c_005fout_005f36.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f36);
      out.write("\" />\n");
      out.write("<param name=\"quality\" value=\"high\">\n");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m:rs(\"mtp-gem-messages\", \"generic.editor.binary.BinaryPropertyEditor_Edit.canNotViewFlash\")}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1));
      out.write("</object>\n");
      out.write("</p>\n");

				} else if (br.getType().indexOf("video/mpeg") != -1) {

      out.write("<p>\n");
      out.write("<object classid=\"clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B\" ");
      out.print(width + height );
      out.write(">\n");
      out.write("  <param name=\"src\" value=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f37 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f37.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f37.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(273,27) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f37.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f37 = _jspx_th_c_005fout_005f37.doStartTag();
      if (_jspx_th_c_005fout_005f37.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f37);
      out.write("\" />\n");
      out.write("  <param name=\"autostart\" value=\"true\" />\n");
      out.write("  <param name=\"type\" value=\"video/mpeg\">\n");
      out.write("  <param name=\"controller\" value=\"true\" />\n");
      out.write("  <param name=\"scale\" value=\"ToFit\">\n");
      out.write("  <embed\n");
      out.write("      src=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f38 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f38.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f38.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(279,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f38.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f38 = _jspx_th_c_005fout_005f38.doStartTag();
      if (_jspx_th_c_005fout_005f38.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f38);
      out.write("\"\n");
      out.write("      scale=\"ToFit\"\n");
      out.write("      ");
      out.print(width + height );
      out.write(">\n");
      out.write("  </embed>\n");
      out.write("</object>\n");
      out.write("</p>\n");

				} else if (br.getType().indexOf("video/quicktime") != -1) {

      out.write("<p>\n");
      out.write("<object classid=\"clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B\"\n");
      out.write("    codebase=\"http://www.apple.com/qtactivex/qtplugin.cab\" ");
      out.print(width + height );
      out.write(">\n");
      out.write("  <param name=\"src\" value=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f39 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f39.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f39.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(291,27) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f39.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f39 = _jspx_th_c_005fout_005f39.doStartTag();
      if (_jspx_th_c_005fout_005f39.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f39);
      out.write("\">\n");
      out.write("  <param name=\"autoplay\" value=\"true\">\n");
      out.write("  <param name=\"type\" value=\"video/quicktime\">\n");
      out.write("  <param name=\"scale\" value=\"ToFit\">\n");
      out.write("  <embed src=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f40 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f40.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f40.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(295,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f40.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f40 = _jspx_th_c_005fout_005f40.doStartTag();
      if (_jspx_th_c_005fout_005f40.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f40);
      out.write("\"\n");
      out.write("       autoplay=\"true\"\n");
      out.write("       scale=\"ToFit\"\n");
      out.write("       type=\"video/quicktime\"\n");
      out.write("       pluginspage=\"http://www.apple.com/quicktime/download/\"\n");
      out.write("       ");
      out.print(width + height );
      out.write(">\n");
      out.write("</object>\n");
      out.write("</p>\n");

				} else if (br.getType().indexOf("audio/mpeg") > -1) {

      out.write("<audio id=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f41 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f41.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f41.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(306,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f41.setValue(propName);
      int _jspx_eval_c_005fout_005f41 = _jspx_th_c_005fout_005f41.doStartTag();
      if (_jspx_th_c_005fout_005f41.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f41);
      out.print(i);
      out.write("\" src=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f42 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f42.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f42.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(306,55) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f42.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f42 = _jspx_th_c_005fout_005f42.doStartTag();
      if (_jspx_th_c_005fout_005f42.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f42);
      out.write("\" controls=\"controls\"></audio>\n");

				} else if (br.getType().indexOf("audio/webm") > -1) {

      out.write("<audio id=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f43 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f43.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f43.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(310,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f43.setValue(propName);
      int _jspx_eval_c_005fout_005f43 = _jspx_th_c_005fout_005f43.doStartTag();
      if (_jspx_th_c_005fout_005f43.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f43);
      out.print(i);
      out.write("\" src=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f44 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f44.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f44.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(310,55) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f44.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f44 = _jspx_th_c_005fout_005f44.doStartTag();
      if (_jspx_th_c_005fout_005f44.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f44);
      out.write("\" controls=\"controls\"></audio>\n");

				} else if (br.getType().indexOf("audio/ogg") > -1) {

      out.write("<audio id=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f45 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f45.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f45.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(314,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f45.setValue(propName);
      int _jspx_eval_c_005fout_005f45 = _jspx_th_c_005fout_005f45.doStartTag();
      if (_jspx_th_c_005fout_005f45.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f45);
      out.print(i);
      out.write("\" src=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f46 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f46.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f46.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(314,55) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f46.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f46 = _jspx_th_c_005fout_005f46.doStartTag();
      if (_jspx_th_c_005fout_005f46.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f46);
      out.write("\" controls=\"controls\"></audio>\n");

				} else if (br.getType().indexOf("video/mp4") > -1) {

      out.write("<video id=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f47 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f47.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f47.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(318,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f47.setValue(propName);
      int _jspx_eval_c_005fout_005f47 = _jspx_th_c_005fout_005f47.doStartTag();
      if (_jspx_th_c_005fout_005f47.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f47);
      out.print(i);
      out.write("\" src=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f48 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f48.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f48.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(318,55) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f48.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f48 = _jspx_th_c_005fout_005f48.doStartTag();
      if (_jspx_th_c_005fout_005f48.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f48);
      out.write("\" controls=\"controls\" ");
      out.print(width + height );
      out.write("></video>\n");

				} else if (br.getType().indexOf("video/webm") > -1) {

      out.write("<video id=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f49 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f49.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f49.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(322,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f49.setValue(propName);
      int _jspx_eval_c_005fout_005f49 = _jspx_th_c_005fout_005f49.doStartTag();
      if (_jspx_th_c_005fout_005f49.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f49);
      out.print(i);
      out.write("\" src=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f50 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f50.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f50.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(322,55) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f50.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f50 = _jspx_th_c_005fout_005f50.doStartTag();
      if (_jspx_th_c_005fout_005f50.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f50);
      out.write("\" controls=\"controls\" ");
      out.print(width + height );
      out.write("></video>\n");

				} else if (br.getType().indexOf("video/ogg") > -1) {
				//音声ファイルでもvideo/oggになることがあるので拡張子で判断
					if (br.getName().indexOf(".") > 1 && br.getName().substring(br.getName().indexOf(".")).toLowerCase().indexOf("ogg") > -1) {

      out.write("<audio id=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f51 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f51.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f51.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(328,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f51.setValue(propName);
      int _jspx_eval_c_005fout_005f51 = _jspx_th_c_005fout_005f51.doStartTag();
      if (_jspx_th_c_005fout_005f51.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f51);
      out.print(i);
      out.write("\" src=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f52 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f52.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f52.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(328,55) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f52.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f52 = _jspx_th_c_005fout_005f52.doStartTag();
      if (_jspx_th_c_005fout_005f52.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f52);
      out.write("\" controls=\"controls\"></audio>\n");

					} else {

      out.write("<video id=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f53 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f53.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f53.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(332,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f53.setValue(propName);
      int _jspx_eval_c_005fout_005f53 = _jspx_th_c_005fout_005f53.doStartTag();
      if (_jspx_th_c_005fout_005f53.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f53);
      out.print(i);
      out.write("\" src=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f54 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f54.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f54.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(332,55) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f54.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f54 = _jspx_th_c_005fout_005f54.doStartTag();
      if (_jspx_th_c_005fout_005f54.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f54);
      out.write("\" controls=\"controls\" ");
      out.print(width + height );
      out.write("></video>\n");

					}
				} else if (br.getType().indexOf("video/x-ms-wmv") != -1) {

      out.write("<video id=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f55 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f55.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f55.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(337,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f55.setValue(propName);
      int _jspx_eval_c_005fout_005f55 = _jspx_th_c_005fout_005f55.doStartTag();
      if (_jspx_th_c_005fout_005f55.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f55);
      out.print(i);
      out.write("\" src=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f56 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f56.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f56.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(337,55) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f56.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f56 = _jspx_th_c_005fout_005f56.doStartTag();
      if (_jspx_th_c_005fout_005f56.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f56);
      out.write("\" controls=\"controls\" ");
      out.print(width + height );
      out.write("></video>\n");

				} else if (br.getType().indexOf("video/flv") > -1) {

      out.write("<video id=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f57 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f57.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f57.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(341,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f57.setValue(propName);
      int _jspx_eval_c_005fout_005f57 = _jspx_th_c_005fout_005f57.doStartTag();
      if (_jspx_th_c_005fout_005f57.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f57);
      out.print(i);
      out.write("\" src=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f58 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f58.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f58.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(341,55) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f58.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f58 = _jspx_th_c_005fout_005f58.doStartTag();
      if (_jspx_th_c_005fout_005f58.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f58);
      out.write("\" controls=\"controls\" ");
      out.print(width + height );
      out.write("></video>\n");

				} else if (br.getType().indexOf("application/octet-stream") > -1) {
					//mimeタイプで動画か判別不可な場合、拡張子で判断
					if (br.getName().indexOf(".") > -1) {
						if (br.getName().substring(br.getName().indexOf(".")).toLowerCase().indexOf("flv") > -1) {
							//拡張子flvなら動画扱い

      out.write("<video id=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f59 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f59.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f59.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(349,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f59.setValue(propName);
      int _jspx_eval_c_005fout_005f59 = _jspx_th_c_005fout_005f59.doStartTag();
      if (_jspx_th_c_005fout_005f59.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f59);
      out.print(i);
      out.write("\" src=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f60 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f60.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f60.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(349,55) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f60.setValue(url(br, ref) );
      int _jspx_eval_c_005fout_005f60 = _jspx_th_c_005fout_005f60.doStartTag();
      if (_jspx_th_c_005fout_005f60.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f60);
      out.write("\" controls=\"controls\" ");
      out.print(width + height );
      out.write("></video>\n");

						}
					}
				}
			}

      out.write("<input type=\"hidden\" name=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f61 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f61.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f61.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(356,27) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f61.setValue(propName );
      int _jspx_eval_c_005fout_005f61 = _jspx_th_c_005fout_005f61.doStartTag();
      if (_jspx_th_c_005fout_005f61.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f61);
      out.write("\" value=\"");
      //  c:out
      org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f62 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
      _jspx_th_c_005fout_005f62.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f62.setParent(null);
      // /jsp/gem/generic/editor/binary/BinaryPropertyEditor_Edit.jsp(356,67) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f62.setValue(br.getLobId() );
      int _jspx_eval_c_005fout_005f62 = _jspx_th_c_005fout_005f62.doStartTag();
      if (_jspx_th_c_005fout_005f62.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f62);
      out.write("\" />\n");
      out.write("</li>\n");

		}

      out.write("</ul>\n");

	} else {
		//HIDDENか更新不可

		if (editor.getDisplayType() != BinaryDisplayType.HIDDEN) {
			request.setAttribute(Constants.OUTPUT_HIDDEN, true);
		}

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "BinaryPropertyEditor_View.jsp", out, false);

		if (editor.getDisplayType() != BinaryDisplayType.HIDDEN) {
			request.removeAttribute(Constants.OUTPUT_HIDDEN);
		}
	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
